import {
  Heading,
  Text,
  Button,
  Avatar,
  RevealFx,
  Column,
  Badge,
  Row,
  Schema,
  Meta,
  Line,
  Media,
} from "@once-ui-system/core";
import { home, about, person, baseURL, routes } from "@/resources";
import { Mailchimp } from "@/components";
import { Projects } from "@/components/work/Projects";
import { Posts } from "@/components/blog/Posts";

export async function generateMetadata() {
  return Meta.generate({
    title: home.title,
    description: home.description,
    baseURL: baseURL,
    path: home.path,
    image: home.image,
  });
}

export default function Home() {
  return (
    <Column maxWidth="m" gap="xl" paddingY="12" horizontal="center">
      <Schema
        as="webPage"
        baseURL={baseURL}
        path={home.path}
        title={home.title}
        description={home.description}
        image={`/api/og/generate?title=${encodeURIComponent(home.title)}`}
        author={{
          name: person.name,
          url: `${baseURL}${about.path}`,
          image: `${baseURL}${person.avatar}`,
        }}
      />
      <Column fillWidth horizontal="center" gap="m">
        {home.featured.display && (
          <RevealFx
            fillWidth
            horizontal="center"
            paddingTop="16"
            paddingBottom="32"
            paddingLeft="12"
          >
            <Badge
              background="brand-alpha-weak"
              paddingX="12"
              paddingY="4"
              onBackground="neutral-strong"
              textVariant="label-default-s"
              arrow={false}
              href={home.featured.href}
            >
              <Row paddingY="2">{home.featured.title}</Row>
            </Badge>
          </RevealFx>
        )}
        <RevealFx translateY="4" fillWidth paddingY="32">
          <Row
            fillWidth
            gap="xl"
            horizontal="between"
            vertical="center"
            s={{ direction: "column", gap: "l" }}
          >
            {/* Left side: Image and Quote */}
            <Column flex={1} horizontal="center" align="center" gap="l" minWidth="200">
              <Column horizontal="center" align="center" gap="m" maxWidth="s">
                <Media
                  src="/images/rubiks_cube_cayley.png"
                  alt="Cayley graph of S₄, generated by (12), (13), and (14). The 24 configurations of the 2×2×2 Rubik's Cube which can be reached by performing 180° half-turns."
                  sizes="(max-width: 560px) 100vw, 400px"
                  radius="m"
                  priority
                  style={{ maxWidth: "100%", height: "auto", display: "block" }}
                />
                <Text
                  wrap="balance"
                  onBackground="neutral-weak"
                  variant="body-default-s"
                  style={{ textAlign: "center", fontStyle: "italic" }}
                >
                  Cayley graph of S₄, generated by (12), (13), and (14). The 24 configurations of the 2×2×2 Rubik's Cube which can be reached by performing 180° half-turns. Interestingly, also an instance of a Nauru graph. Credit: Jim Fowler
                </Text>
              </Column>
              <Column horizontal="center" align="center" gap="s" maxWidth="s">
                <Text
                  wrap="balance"
                  onBackground="neutral-weak"
                  variant="heading-default-m"
                  style={{ fontStyle: "italic", textAlign: "center" }}
                >
                  "What if I fall? Oh, but my darling, what if you fly?"
                </Text>
                <Text
                  onBackground="neutral-weak"
                  variant="body-default-s"
                  style={{ textAlign: "center" }}
                >
                  — Erin Hanson
                </Text>
              </Column>
            </Column>

            {/* Right side: Headline and Subline */}
            <Column flex={1} gap="m" vertical="center" horizontal="center" align="center">
              <Heading wrap="balance" variant="display-strong-l" style={{ textAlign: "center" }}>
                {home.headline}
              </Heading>
              <Text wrap="balance" onBackground="neutral-weak" variant="heading-default-xl" style={{ textAlign: "center" }}>
                {home.subline}
              </Text>
            </Column>
          </Row>
        </RevealFx>
        <RevealFx paddingTop="12" delay={0.4} horizontal="center" paddingLeft="12">
          <Button
            id="about"
            data-border="rounded"
            href={about.path}
            variant="secondary"
            size="m"
            weight="default"
            arrowIcon
          >
            <Row gap="8" vertical="center" paddingRight="4">
              {about.avatar.display && (
                <Avatar
                  marginRight="8"
                  style={{ marginLeft: "-0.75rem" }}
                  src={person.avatar}
                  size="m"
                />
              )}
              {about.title}
            </Row>
          </Button>
        </RevealFx>
      </Column>
      <RevealFx translateY="16" delay={0.6}>
        <Projects range={[1, 1]} />
      </RevealFx>
      {routes["/blog"] && (
        <Column fillWidth gap="24" marginBottom="l">
          <Row fillWidth paddingRight="64">
            <Line maxWidth={48} />
          </Row>
          <Row fillWidth gap="24" marginTop="40" s={{ direction: "column" }}>
            <Row flex={1} paddingLeft="l" paddingTop="24">
              <Heading as="h2" variant="display-strong-xs" wrap="balance">
                Latest from the blog
              </Heading>
            </Row>
            <Row flex={3} paddingX="20">
              <Posts range={[1, 2]} columns="2" />
            </Row>
          </Row>
          <Row fillWidth paddingLeft="64" horizontal="end">
            <Line maxWidth={48} />
          </Row>
        </Column>
      )}
      <Projects range={[2]} />
      <Mailchimp />
    </Column>
  );
}
